#!/bin/bash
# Copyright 2013 Ronoaldo JLP (http://www.ronoaldo.net)
# 
#   Licensed under the Apache License, Version 2.0 (the 'License');
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an 'AS IS' BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


dig_query() {
	domain="$1"
	dig $domain A $domain TXT \
		www.$domain CNAME www.$domain A \
		$domain MX mx.$domain MX |\
	grep -v -e ^';' -e '^$' |\
	awk '{ printf "%-30s\t%s\n",$1,substr($0, index($0, $3))}' |\
	sort | uniq
}

if [ -z $1 ] ; then
	echo "Use $0 naked_domain"
fi

dig_query "$1"
