#!/bin/bash
# Copyright 2013 Ronoaldo JLP (http://www.ronoaldo.net)
# 
#   Licensed under the Apache License, Version 2.0 (the 'License');
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an 'AS IS' BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# 
# Simple utility to check diferences in two JAR files.
# 
# Copyrigh (C) 2013 Ronoaldo JLP (http://www.ronoaldo.net)

set -e

PROGRAM="$(basename $0)"
VERSION="1.0"
AUTHOR="Ronoaldo JLP"

# Print help and exits
usage() {
	cat <<EOF
$PROGRAM $VERSION - Copyright (C) 2013 $AUTHOR
Displays diferences in two jar/zip files.

Use $PROGRAM jar1 jar2

Examples:
	jardiff commons-collections-3.2.jar commons-collections-3.2.1.jar

EOF
	exit 1
}

# List jar content paths, alphabetically
ls_jar() {
	unzip -l "$1"  |  awk '{print $4}' | sort
}

if [ x"" == x"$1" -o x"" == x"$2" ] ; then
	usage
fi

exec diff -Naur <( ls_jar $1 ) <( ls_jar $2)
