#!/bin/bash

set -e

LICENSE="# Copyright $(date +%Y) Ronoaldo JLP (http://www.ronoaldo.net)
# 
#   Licensed under the Apache License, Version 2.0 (the 'License');
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an 'AS IS' BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
"

has_license() {
	if grep -qi "licensed under the apache license" $1 ; then
		return 0
	else 
		return 1
	fi
}

apply_license() {
	shebang="$(head -n 1 $1)"
	echo "$shebang" > $1.new
	echo "$LICENSE" >>  $1.new
	grep -v "$shebang" $1 >> $1.new
	chmod --reference=$1 $1.new
	echo License $2 applied to $1.new
}

for file in $@ ; do
	if ! has_license $file ; then
		echo "Appliyng license to $file ... "
		apply_license $file
	else
		echo "$file has license"
	fi
done
