" ~/.vimrc - Ronoalado JLP

" Creative Commons CC-BY-SA

" ** Funções úteis **

" Tabs normais - \t
fu! SetupNormalTabs()
    set sw=8 ts=8 st=8 noet si ai
endfu

" Tabs com 4 espaços
fu! SetupSpaceTabs()
    set sw=4 ts=4 st=4 et si ai
endfu

" Tabs com 2 espaços
fu! Setup2SpaceTabs()
    set sw=2 ts=2 st=2 et si ai
endfu

" Mercurial
fu! HgPull()
  !hg pull
endfu

fu! HgPush()
  !hg push
endfu

" ** Comandos **

" JUnit
fu Junit()
  let unit_test = expand('%:t:r')
	belowright split | enew 
  echo "Running junit test **" . unit_test . " ..."
  execute 'r!mvn -o -DskipTests=false -Dtest=**' . unit_test . ' -DfailIfNoTests=false test'
endfu
command Junit call Junit()

" Gwt
command Gwtc !mvn -o gwt:compile

" Review your changes
fu Review()
  belowright split | enew | execute 'r!hg diff --git' | setfiletype diff
endfu
command Review call Review()

" Ctags
fu IndexWorkspace()
  echo "Indexing .tags file ..."
  !rm -vf ~/workspace/.tags && find ~/workspace/ -type f -iname '*.java' | xargs ctags -a -f ~/workspace/.tags  -L - --totals
endfu
command IndexWorkspace call IndexWorkspace()

" Code Snippets
fu InstallSnippets()
  echo "Baixando e instalando Code Snippets"
  !cd /tmp && wget https://github.com/csexton/snipmate.vim/archive/master.zip && unzip master.zip && mkdir -p ~/.vim && mv snipmate.vim-master/* ~/.vim
endfu
command InstallSnippets call InstallSnippets()

" ** IDE **

" Mapeamento de tipos de arquivo especiais
au BufRead,BufNewFile *.bsh call setfiletype java

" Mapeamento de tabs por tipos especiais de arquivos
au BufRead,BufNewFile *.py call SetupSpaceTabs()
au BufRead,BufNewFile Makefile call SetupNormalTabs()
au BufRead,BufNewFile makefile call SetupNormalTabs()
au BufRead,BufNewFile *.xml call SetupNormalTabs()
au BufRead,BufNewFile *.txt call Setup2SpaceTabs()
au BufRead,BufNewFile */.vimrc call Setup2SpaceTabs()

" Configura ~/workspace para usar com o Maven
augroup workspace
  if !exists("s:workspace_init")
    let s:workspace_init = 1
    autocmd BufNewFile,BufRead */workspace/* call SetupNormalTabs()
    autocmd BufNewFile,BufRead */workspace/* set tags=~/workspace/.tags
    autocmd BufNewFile,BufRead */workspace/* cd <afile>:~:s?\~/workspace/\([^/]\+\)/.*?\~/workspace/\1?
    autocmd BufNewFile,BufRead */workspace/* compiler ant
    autocmd BufNewFile,BufRead */workspace/* set makeprg=mvn\ -q\ -o\ test-compile\ -f\ ./pom.xml | cw
    autocmd BufNewFile,BufRead */workspace/* set errorformat=\[ERROR]\ %f:[%l\\,%v]\ %m
    autocmd BufNewFile,BufRead */workspace/* map! <C-F11> :start mvn -f pom.xml appengine:devserver <CR>
    autocmd BufNewFile,BufRead */workspace/* map <C-F11> :start mvn -f pom.xml appengine:devserver <CR>
    autocmd BufNewFile,BufRead */workspace/* noremap  <C-F5> :make<CR>
    autocmd BufNewFile,BufRead */workspace/* vnoremap <C-F5> <C-C>:make<CR>
    autocmd BufNewFile,BufRead */workspace/* inoremap <C-F5> <C-O>:make<CR>
  endif
augroup END

" ** Atalhos do Teclado **

" Mapeia o CTRL+S para salvar o arquivo
silent !stty stop '' -ixoff
noremap  <silent> <C-S>	:update<CR>
vnoremap <silent> <C-S>	<C-C>:update<CR>
inoremap <silent> <C-S> <C-O>:update<CR>

" Comandos do Mercurial
noremap  <silent> <C-P>	:call HgPull()<CR>
vnoremap <silent> <C-P>	<C-C>:call HgPull()<CR>
inoremap <silent> <C-P> <C-O>:call HgPull()<CR>

noremap  <silent> <C-U>	:call HgPush()<CR>
vnoremap <silent> <C-U>	<C-C>:call HgPush()<CR>
inoremap <silent> <C-U> <C-O>:call HgPush()<CR>

" ** Opções de configuração gerais **

" Configurações padrão para usar no Vim/GVim
syntax on
set modeline
set modelines=5
set nomousehide
set wrap
set number
set hlsearch
set mouse=a
